# Generated by Django 2.2.4 on 2019-10-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='amt_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='post',
            name='amt_sought',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='post_status',
            field=models.CharField(default='Funding needed', max_length=100),
        ),
    ]
