# Generated by Django 2.2.4 on 2019-10-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191030_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='amt_raised',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='amt_sought',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
