# Generated by Django 2.2.4 on 2019-10-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191030_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Postcode'),
        ),
    ]
