# Generated by Django 2.2.4 on 2019-10-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191030_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='amt_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Amount raised so far (SGD)'),
        ),
        migrations.AddField(
            model_name='post',
            name='amt_sought',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Amount needed for project (SGD)'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_status',
            field=models.CharField(default='Funding needed', max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
