# Generated by Django 2.2.4 on 2019-11-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191030_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='amt_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Amount raised so far (SGD)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='amt_sought',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Amount needed for project (SGD)'),
        ),
    ]
